// Auto-generated by LibreLane
module mt_cpu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input swap_tgrp,
  output[31:0] result,
  output[31:0] pcw
);
endmodule
